name: rachadinha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_injector: ^2.0.5
  flutter:
    sdk: flutter
  result_command: ^1.3.0
  result_dart: ^2.0.0
  routefly: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
