name: rachadinha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_injector: ^2.0.5
  cloud_firestore: ^5.6.5
  dio: ^5.8.0+1
  dotted_dashed_line: ^0.0.3
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  lucid_validation: ^1.2.5
  result_command: ^1.3.0
  result_dart: ^2.0.0
  routefly: ^3.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
