// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/auth/login',
        uri: Uri.parse('/auth/login'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: '/auth/register',
        uri: Uri.parse('/auth/register'),
        routeBuilder: b1Builder,
      ),
      RouteEntity(
        key: '/history',
        uri: Uri.parse('/history'),
        routeBuilder: b2Builder,
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: b3Builder,
      ),
      RouteEntity(
        key: '/qrcode',
        uri: Uri.parse('/qrcode'),
        routeBuilder: b4Builder,
      ),
    ];

const routePaths = (
  path: '/',
  auth: (
    path: '/auth',
    login: '/auth/login',
    register: '/auth/register',
  ),
  history: '/history',
  home: '/home',
  qrcode: '/qrcode',
);
